### ISSUE TITLE
md5sum: standard input: no properly formatted MD5 checksum lines found

### ISSUE THREAD

**Issue by chenxizhang** [hgeraldino/cxf-fediz-docker#1]
please help to this error message,thank you

![image](https://user-images.githubusercontent.com/1996954/35955467-82a1f4f8-0cca-11e8-8a9b-74afb2d9d702.png)

**Comment by hgeraldino** [comment]
@chenxizhang I just had a chance to look at this today. I've fixed the versions and the docker images are building now.
